// Test definitions. Do NOT edit this file!
#include <iostream>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include <catch2/catch.hpp>

#include "../Fraccion.hpp"
#include "../opFraccion.hpp"

TEST_CASE("Ex1", "[Constructores]")
{
    Fraccion f1, f2(2,3);
    INFO("FUNCIONALIDAD ESPERADA: El constructor por defecto debe inicializar la fracción con numerador 1 y denominador 2.");
    INFO("PROGRAMACIÓN: Constructor: Fraccion() debe asignar num=1 y den=2; getNum() y getDen() deben devolver esos valores.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Inicializa los atributos en el constructor por defecto y verifica con los getters. ");
    
    REQUIRE(f1.getNum()==1);
    REQUIRE(f1.getDen()==2);

    INFO("FUNCIONALIDAD ESPERADA: El constructor con parámetros debe inicializar la fracción con los valores proporcionados.");
    INFO("PROGRAMACIÓN: Constructor: Fraccion(int num, int den) debe asignar los atributos según los argumentos recibidos.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Verifica la asignación de parámetros al campo correspondiente y prueba con getters.");
    
    REQUIRE(f2.getNum()==2);
    REQUIRE(f2.getDen()==3);
}

TEST_CASE("Ex2", "[Getters y Setters]")
{
    Fraccion f(5,4);

    INFO("FUNCIONALIDAD ESPERADA: getNum() debe retornar el numerador y getDen() el denominador inicializados.");
    INFO("PROGRAMACIÓN: Implementa int getNum() y int getDen() que devuelvan los atributos num y den respectivamente.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Verifica que los getters no modifiquen estado y devuelvan valores correctos.");
    
    REQUIRE(f.getNum()==5);
    REQUIRE(f.getDen()==4);

    f.setNum(2);
    f.setDen(3);

    INFO("FUNCIONALIDAD ESPERADA: setNum() y setDen() deben modificar correctamente los valores de la fracción.");
    INFO("PROGRAMACIÓN: Implementa void setNum(int) y void setDen(int) que asignen los valores recibidos a num y den.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Asegúrate de usar las asignaciones correctas y valida con los getters después de setear.");
    
    REQUIRE(f.getNum()==2);
    REQUIRE(f.getDen()==3);
}

TEST_CASE("Ex3", "[Calculando el valor real]")
{
    Fraccion f;

    INFO("FUNCIONALIDAD ESPERADA: calcValorReal() debe retornar el valor decimal de la fracción.");
    INFO("PROGRAMACIÓN: Implementa double calcValorReal() que retorne (double)num/den o equivalente para obtener un double.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Realiza el casteo a double para evitar división entera.");
    
    REQUIRE(f.calcValorReal()==0.5);
}

TEST_CASE("Ex4", "[Suma de Fracciones")
{
    Fraccion f1(2,5), f2(3,10);
    Fraccion f3=sumaFracciones(f1, f2);

    INFO("FUNCIONALIDAD ESPERADA: sumaFracciones() debe retornar la suma correcta de dos fracciones y simplificar el resultado.");
    INFO("PROGRAMACIÓN: Función: Fraccion sumaFracciones(Fraccion a, Fraccion b) debe sumar usando fórmula ns = a.num*b.den + b.num*a.den; ds = a.den*b.den; y simplificar.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Implementa la fórmula de suma y llama a simplifica() antes de devolver la fracción.");
    
    REQUIRE(f3.getNum()==7);
    REQUIRE(f3.getDen()==10);
}

TEST_CASE("Ex5", "[Arreglo de fracciones")
{
    Fraccion af[5];

    af[0].setNum(1);af[0].setDen(2);
    af[1].setNum(2);af[1].setDen(3);
    af[2].setNum(3);af[2].setDen(4);
    af[3].setNum(4);af[4].setDen(5);
    af[4].setNum(5);af[4].setDen(6);

    for (auto i=0; i<5;i++)
    {
        af[i].imprimeFraccion();
    }

    std::cout << "Sumando 1/2 + 2/3" << "\n";   

    af[2]=sumaFracciones(af[0], af[1]);

    std::cout << "Resulta en ";
    af[2].imprimeFraccion();

    INFO("FUNCIONALIDAD ESPERADA: Al sumar 1/2 + 2/3 el resultado debe ser 7/6 y almacenarse correctamente en el arreglo.");
    INFO("PROGRAMACIÓN: Usa sumaFracciones(Fraccion, Fraccion) y asigna el resultado a af[2] antes de consultar sus getters.");
    INFO("SUGERENCIA DE PROGRAMACIÓN: Verifica la asignación en el arreglo y la simplificación del resultado.");

    REQUIRE(af[2].getNum()==7);
    REQUIRE(af[2].getDen()==6);
}
